### ISSUE TITLE
Metamask connect is failing

### ISSUE THREAD

**Issue by 1ucas-eng** [TenKeyLabs/dappwright#202]
**Describe the bug**
I tried to connect metamask wallet with below code.

```
    dappwright.bootstrap('chrome', {
      wallet: 'metamask',
      version: MetaMaskWallet.recommendedVersion,
      seed: 'seed',
      headless: false,
    })
```

But it gives below error

![image](https://github.com/TenKeyLabs/dappwright/assets/57629106/2d5d271f-24cc-4e75-8a3d-c99634b0b486)

**To Reproduce**
1. Local
I setup playwright and dappwright npm modules
And used below code for wallet connect

```
export const test = baseTest.extend<{
  context: BrowserContext;
  wallet: Dappwright;
}>({
  context: async ({}, use) => {
    // Launch context with extension
    const [_wallet, _, context] = await dappwright.bootstrap('chrome', {
      wallet: 'metamask',
      version: MetaMaskWallet.recommendedVersion,
      seed: 'spawn frozen dress myth ability hidden flush snow noodle tomorrow spirit drum',
      headless: false,
    });

    await use(context);
  },

  wallet: async ({ context }, use) => {
    const metamask = await dappwright.getWallet('metamask', context);

    await use(metamask);
  },
});
```

2.Current dappwright repo
I cloned current repo and run test, it also gives same error

**Expected behavior**

**Screenshots**

**System:**

- OS: MacOS
- OS version 11.4
- NodeJs version v18.15.0
- dAppwright version ^2.4.0
- testing framework jest
- testing framework version ^29.5.0

**Additional context**

**Comment by osis** [comment]
Thanks for the issue! I've seen this with the later versions of the plugin. Hoping a version bump helps. Not eager to implement some reload-on-crash logic. 😅

**Comment by alejogranerorequest** [comment]
The issue persists in the version 2.3

**Comment by osis** [comment]
Should be solved with Metamask 11. Seems to be more stable.

**Comment by osis** [comment]
Metamask has been bumped and looks good. Going to close this for now.
