### ISSUE TITLE
Cannot download the recommended version

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#227]
**Describe the bug**
It cannot download the Metamask recommended version: 10.25. I'm facing the following error message before running any test:

'Version v10.25.0 not found!'

**System:**

- OS: [iOS]
- OS version [e.g. 14]
- NodeJs version [v18.17.0]
- dAppwright version  [^2.4.0],
- testing framework: [playwright]
- testing framework version [1.38.0]

**Additional context**

**Comment by julia-script** [comment]
I have the same issue, that's because the recommended version fell to the second page of the release query.

https://github.com/TenKeyLabs/dappwright/blob/main/src/wallets/metamask/metamask.ts#L29

As a quick fix I set the version to "10.26.2" which still worked fine for me

**Comment by alejogranerorequest** [comment]
It would be awesome if the devs fix the v10.25.0, the v10.26.2 doesn't work for me. It is weird because it started to fail from one moment to another without changing anything in the code.

**Comment by julia-script** [comment]
The sudden stop is because MetaMask pushed a new release, which pushed the recommended version to the second page of the release query, and this package is only querying the first page. 

I’m open to push a quick fix if the author is open to it

**Comment by alejogranerorequest** [comment]
If you can do that, it would be great 🙏

**Comment by osis** [comment]
We've bumped to the latest version! Skills be good to go if you upgrade.

**Comment by osis** [comment]
@julia-script  contributions are always welcome.

**Comment by osis** [comment]
Seems to be related to https://github.com/TenKeyLabs/dappwright/issues/234.
