### ISSUE TITLE
Metamask switch account stuck

### ISSUE THREAD

**Issue by panteo** [TenKeyLabs/dappwright#233]
When trying to switch account in Metamask it gets stuck at account selection list.

**To Reproduce**

1. `yarn run test:ci test/2-wallet.spec.ts:45`
1. See error

![Screenshot from 2023-10-23 13-18-30](https://github.com/TenKeyLabs/dappwright/assets/6220943/539cb68b-39e0-4160-95fb-3395867dee96)

**Expected behavior**

It should select the account and close the dialog.

**System:**

- OS Debian
- OS version 11.8
- NodeJs version v18.2.0
- dAppwright version 2.4.1

**Logs**

```
1) [MetaMask] › test/2-wallet.spec.ts:46:11 › when interacting with the wallet › account management › switchAccount › should switch accounts 

    Error: elementHandle.click: Target closed
    =========================== logs ===========================
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="mm-box mm-modal-content multichain-accoun…>…</div> from <div class="mm-modal">…</div> subtree intercepts pointer events
    retrying click action, attempt #1
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="mm-box mm-box--display-flex mm-box--justi…>…</div> from <div class="mm-modal">…</div> subtree intercepts pointer events
    retrying click action, attempt #2
      waiting 20ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="mm-box mm-box--display-flex mm-box--justi…>…</div> from <div class="mm-modal">…</div> subtree intercepts pointer events
    retrying click action, attempt #3
      waiting 100ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="mm-box mm-modal-content multichain-accoun…>…</div> from <div class="mm-modal">…</div> subtree intercepts pointer events
...
```

**Additional context**

I was able to fix the problem by forcing the click [here](https://github.com/TenKeyLabs/dappwright/blob/553d93f5f4b77aaee5939e01e4907f3aed928cb2/src/helpers/actions.ts#L10), but I am not sure this is a good solution:

```
  await element.click({ force: true });
```

**Comment by osis** [comment]
Took a bit of a closer look. If this indeed caused by wanting to switch to a network that contains the same string, I think a quick fix of forcing a click should be fine for now. Ultimately, would like to throw an error warning the user they sent an ambiguous name selection through.

**Comment by alejogranerorequest** [comment]
I think here you have a similar issue than me when I try to connect to "Goerli", but with this command: wallet.switchNetwork("Goerli"). I think the fix is adding ".first()" before clicking on the network. It seems it can't click specifically on "Goerli" because of a duplicate identifier. Is possible to create a PR for that?

**Comment by osis** [comment]
Yup, should be able to get to this in the next day or two unless someone beats me to it!

**Comment by alejogranerorequest** [comment]
@osis , I decided to create a new bug ticket to manage the issue of the switch network in a different one:
https://github.com/TenKeyLabs/dappwright/issues/240#issue-1969060589
