### ISSUE TITLE
Missing step for closing the settings

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#246]
During the set up, when the extension moves to the settings in order to enable the testing networks, it never moves back and the execution of the setup fails. A step for closing the settings is missing.

- dAppwright version [2.5.2]
- testing framework [Playwright]
- testing framework version [1.38.0]

**Comment by alejogranerorequest** [comment]
@osis , is possible to add that step?

**Comment by osis** [comment]
Definitely! dappwright has the ability to click on the logo at the top of the window to return home.

**Comment by alejogranerorequest** [comment]
@osis, if you can add that step I will appreciate 🙏
