### ISSUE TITLE
Cannot switch network using the popup

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#256]
**Describe the bug**
The confirmNetworkSwitch() method doesn't work, it does nothing, and the test fails.

**Logs**

```shell
Error: browserContext.waitForEvent: Context closed

      186 |       await walletConnectModal.getMetamask().click();
      187 |       await wallet.approve();
      188 |       await wallet.confirmNetworkSwitch()
```

**System:**

- OS version [e.g. 22]
- NodeJs version [e.g v15.8.0]
- dAppwright version [e.g. 2.5.4]
- testing framework [e.g Playwright]
- testing framework version [e.g 1.38.0]

**Comment by alejogranerorequest** [comment]
@osis, do you know if something is not working with that method?

**Comment by osis** [comment]
Hmmm when you say the tests are failing, I don't see that happening in the Dappwright tests. Is there a way to replicate?

**Comment by alejogranerorequest** [comment]
I think just trying to switch the network from goerli to polygon, for example.
