### ISSUE TITLE
Do not setup Metamask before each test

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#265]
I want to set up my metamask wallet before all the test runs in my test suite. Do we have a way to achieve it?
Using "test" from dappwright after every test, the extension is connected from scratch. I want to do that step once.

@osis , do you know if it is possible? 
**System:**

- OS version [e.g. 22]
- NodeJs version [e.g v15.8.0]
- dAppwright version [e.g. 2.5.5]
- testing framework [e.g Playwright]
- testing framework version [e.g 26.0]

**Comment by osis** [comment]
It's a good question. There are a bunch of ways to do it (global setup, helper functions, etc). After a few iterations, you can see how Dappwright runs its own tests. I found this to be the best way to do the setup while still being able to debug issues during the setup phase.

https://github.com/TenKeyLabs/dappwright/blob/main/test/helpers/walletTest.ts
https://github.com/TenKeyLabs/dappwright/blob/ae7e53da7b77ee6afaf33b12b2264bb2976dcf84/test/1-init.spec.ts#L2

**Comment by alejogranerorequest** [comment]
Hey @osis, thank you for your help! 
I want to start a fresh sharedBrowser between spec files, in the afterAll() if I use await page.context().close(), in the first execution of the first test in the next spec file, it fails because it cannot find the browser context. Do you know how to start a fresh sharedContext at the beginning of every spec file but sharing that context within the test in the file?

**Comment by alejogranerorequest** [comment]
Hey @osis , if you remove the L5, you must remove other lines like 12, 32, and 35, right?

**Comment by osis** [comment]
Looks like it's close. The idea is to remove the `sharedBrowserContext` variable. That's the only global state that's carrying context across tests. If you remove it and adjust the lines affected, you should be in a good place.

**Comment by alejogranerorequest** [comment]
Working!
