### ISSUE TITLE
Implement switchNetwork & confirmNetworkSwitch for Coinbase

### ISSUE THREAD

**Issue by osis** [TenKeyLabs/dappwright#27]
**Describe the bug**
The `confirmNetworkSwitch` action isn't implemented for Coinbase. This is due to a bug in Coinbase Wallet 3.0.4 where the `wallet_switchEthereumChain` call doesn't recognize custom networks that have been added and returns "unknown network".

**Additional context**
Keeping an eye on https://github.com/osis/coinbase-wallet-archive/releases for new versions will indicate when this can be attempted again.

**Comment by CustomerTeam001** [comment]
@osis We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77
