### ISSUE TITLE
"Sign in" request method

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#271]
Some sites request a click on a sign-in button after approving the connection with "wallet.approve()". Could you add a method to click on "Sign In"? 

Another option is to modify the wallet.approve() method to manage this sign in request

cc: @osis 
<img width="401" alt="Screenshot 2023-12-13 at 16 55 54" src="https://github.com/TenKeyLabs/dappwright/assets/110841882/4188d5d9-e153-4751-9997-925abf6fdf4d">
<img width="453" alt="Screenshot 2023-12-13 at 16 55 49" src="https://github.com/TenKeyLabs/dappwright/assets/110841882/60486b99-4f47-4e13-a944-53884f741b71">

**Comment by osis** [comment]
oh, that's interesting. What is the complete flow for this? Does it happen before or after you approve?

**Comment by alejogranerorequest** [comment]
Yes, it happens right after you approve.

**Comment by alejogranerorequest** [comment]
A simple method for clicking over it could be enough.
This is the HTML code for the Sign in button:
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Sign-In</button>

**Comment by osis** [comment]
alright cool. Thanks for the context.

**Comment by alejogranerorequest** [comment]
Hey @osis , do you have an update on this?

**Comment by osis** [comment]
another easy one for someone to contribute to the project. 🙏🏾  My next cycle of time for this will be through the holidays, so I'll pick up whatever is open.
