### ISSUE TITLE
Signin method

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#288]
Hey @osis , thank you for helping with the signing method, but checking deeply, the sign-in interface is part of the approve() process, which is very weird. Do you know if that can be added to the approval process without breaking the usual approval flow?

**Comment by osis** [comment]
approve is used to confirm a number of one-off use cases. It's a general confirmation action. Sign has been made to work whether the connection approval pops up or not. Which part of the flow is breaking for you? The idea is that you would be able to change approve with sign in and it should work. There hasn't been a change to the approve flow.

**Comment by alejogranerorequest** [comment]
Using the same Metamask popup for the approval process, the sign in screen is shown as part of the approval flow.

**Comment by osis** [comment]
yes, you would use the signin action method and it will do approval as a prerequisite to complete the action.

**Comment by alejogranerorequest** [comment]
I could make it work locally with wallet.signin(), but if I run it in CI, I get this error message: _TypeError: wallet.signin is not a function_. Is there a missing reference to the method?

**Comment by osis** [comment]
Hmmmm sounds like your CI is running the wrong version of Dappwright? That's the only think I can think of that would cause that error. 🤔

**Comment by alejogranerorequest** [comment]
Yes, you're right, I had version #2.5.5 and the latest one is #2.7.1. Now it's working, thank you!
