### ISSUE TITLE
Add other extensions to dappwright bootstrap

### ISSUE THREAD

**Issue by IGoRFonin** [TenKeyLabs/dappwright#292]
**Is your feature request related to a problem? Please describe.**
Need to install few another extensions for test.

**Describe the solution you'd like**
Add new options parameter to `dappwright.bootstrap`

**Comment by osis** [comment]
out of curiosity in terms of evolution of that interface, what is the use case for these other extensions?

**Comment by IGoRFonin** [comment]
I use the "webrtc control" extension to disable webrtc. This reduces bot detection in playwright if you use a proxy.
