### ISSUE TITLE
Add new network timeout issue

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#301]
Hey @osis , I have an issue trying to add Polygon mainnet network using wallet.addnetwork(), this is the issue:

<img width="1189" alt="Screenshot 2024-01-31 at 13 23 00" src="https://github.com/TenKeyLabs/dappwright/assets/110841882/4ce55331-6d28-4d53-8f40-6583ad6d9c07">

Polygon is shown in the list un the previous step before adding a network and providing all the details.
Is it possible to add a network from that list? Like this:
wallet.addNetwork("Polygon mainnet").

Playwright version: 1.41.1
Dappwright version: 2.8.0

**Comment by witem** [comment]
Similar problem in my case 
![image](https://github.com/TenKeyLabs/dappwright/assets/1782530/e264c503-5812-4d9d-ad7b-b9d33b1a39f6)
- Metamask version 11.7.5
- Playwright version: 1.41.2
- Dappwright version: 2.8.1

**Comment by osis** [comment]
Hhmmm this is a tricky situation since they are the pre-loaded networks. This functionality use to work but I guess they started guarding duplicates more aggressively? 🤔

**Comment by witem** [comment]
> Hhmmm this is a tricky situation since they are the pre-loaded networks. This functionality use to work but I guess they started guarding duplicates more aggressively? 🤔

In my case this was related to some unresponsive RPC, which cause timeout on other versions of metamask

**Comment by osis** [comment]
I'm going to close this then as it's something outside the control of this lib.
