### ISSUE TITLE
dappwright.bootstrap hangs in metamask view; coinbase works

### ISSUE THREAD

**Issue by Jo-Chris** [TenKeyLabs/dappwright#321]
**Describe the problem**

**EDIT: it works flawlessly with CoinbaseWallet, only Metamask is stuck.**

After calling dappwright.bootstrap, it stops in the settings section. How to go from here? The configuration is from the docs.

![image](https://github.com/TenKeyLabs/dappwright/assets/44052255/d583d511-02bc-45e7-ab4c-a7ceeb3b9e28)

inside context: () 
```

    const [wallet, _, context] = await dappwright.bootstrap("", {
      wallet: "metamask",
      version: MetaMaskWallet.recommendedVersion,
      seed: MNEMN_PHRASE,
      headless: false,
      showTestNets: true,
    });

    console.log("--- This is never reached");
    await wallet.addNetwork({
      networkName: "Sepolia",
      rpc: "https://sepolia.gateway.tenderly.co",
      chainId: 11155111,
      symbol: "ETH",
    });
    await use(context);
  },
```

**System:**

- OS: [e.g. iOS] macos
- OS version [e.g. 22] Sonoma 14
- NodeJs version [e.g v15.8.0] 18
- dAppwright version [e.g. 2.2.0] 2.8.2
- testing framework [e.g jest] jest, playwright
- testing framework version [e.g 26.0] 29.1.2 | 1.42.1

**Comment by osis** [comment]
Hello! That's an odd spot for that to get stuck. Can you run playwright in debug mode to see which element/instruction it's waiting for? Also, did you change the targeted MetaMask version?

**Comment by dlaxcess** [comment]
Hi, I've got the same issue, and when i try to run playwright in debug mode, I get stucked earlier juste after metamask installation (before account creation)

**Comment by dlaxcess** [comment]
Hi @osis It seems to be linked solely to Metamask... using the CoinbaseWallet extension works perfectly.

**Comment by osis** [comment]
this should be fixed in the latest version.
