### ISSUE TITLE
Metamask recommended version

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#337]
I'm getting this issue: 'Version v11.10.0 not found!'

Could you update the recommended version?

- OS: [iOS]
- OS version [14.5]
- NodeJs version [v18.18.0]
- dAppwright version [2.8.2]
- testing framework [playwright]
- testing framework version [1.38]

@osis

**Comment by Admin661** [comment]
> 
> 
> I'm getting this issue: 'Version v11.10.0 not found!'
> 
> 
> 
> Could you update the recommended version?
> 
> 
> 
> - OS: [iOS]
> 
> - OS version [14.5]
> 
> - NodeJs version [v18.18.0]
> 
> - dAppwright version [2.8.2]
> 
> - testing framework [playwright]
> 
> - testing framework version [1.38]
> 
> 
> 
> @osis 
> 
> 

Hello @alejogranerorequest sorry for the inconvenience caused! You'll have to rectify with the metamask loptimal weblink.

**Comment by osis** [comment]
Yes! There was a related issue about this that'll track down.

**Comment by alejogranerorequest** [comment]
Thanks, I've manually tried to force to v11.15.6 but it is constantly crashing on the tests. I'll wait for the new Dappwright's version

**Comment by ekrata-main** [comment]
this is also failing for chromium
