### ISSUE TITLE
Metamask version issue

### ISSUE THREAD

**Issue by alejogranerorequest** [TenKeyLabs/dappwright#344]
I have a lot of instabilities with the last version 2.8.4, the recommended version is 11.16.3 and the last one available in Chrome is 11.15.6

@osis , could you downgrade the recommended version to 11.15.6?

**Comment by alejogranerorequest** [comment]
It can't finish the wallet setup, it gets stuck after importing the wallet using the secret words; I can't switch networks or accounts.

**Comment by alejogranerorequest** [comment]
![test-failed-4](https://github.com/TenKeyLabs/dappwright/assets/110841882/c53017b6-b3d2-4d14-938a-be9b8540405c)
It fails after this page, I took it from the trace log.

**Comment by alejogranerorequest** [comment]
Seems to be working after upgrading to last playwright version. Keep you posted.

**Comment by alejogranerorequest** [comment]
I still face instabilities on CI, do you know if something is missing @osis ?

**Comment by johanneskares** [comment]
Had the same issue, I created a lib that uses a headless mock wallet for testing: https://github.com/johanneskares/wallet-mock

**Comment by osis** [comment]
Hmmm seems like there is some new variable behaviour in the setup. Should be able to replace in tests.

**Comment by osis** [comment]
I wouldn't necessarily classify as a version issue, more of a random case that isn't handled. But you can always downgrade the version your running in the config.

**Comment by osis** [comment]
> I still face instabilities on CI, do you know if something is missing @osis ?

there are known issues with playwright and popups in github actions. I suggest setting up your CI tests to be similar to this repo (retry logic) until they are solved.

**Comment by osis** [comment]
> ![test-failed-4](https://private-user-images.githubusercontent.com/110841882/336543006-c53017b6-b3d2-4d14-938a-be9b8540405c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTUzOTMsIm5iZiI6MTcxOTE5NTA5MywicGF0aCI6Ii8xMTA4NDE4ODIvMzM2NTQzMDA2LWM1MzAxN2I2LWIzZDItNGQxNC05MzhhLWJlOWI4NTQwNDA1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwMjExMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzljYmZlZjgzNTBhMGNhMTQyMjJhYjM5N2FlM2VkOWNlMTMzNDM4NjJlYmZkZDE0MThiMjZhYjVhOWZjNjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.no8-eLsCmN4ig-xAEAuqvWOx_8nXd4wcCe5XbDhchZk) It fails after this page, I took it from the trace log.

When it comes to this screen in particular though. I did find it odd since it's not a popup so I looked a bit deeper. Looks like this is a bit of a bug(?) in MetaMask where the behaviour changes only for the first wallet setup after the extension has been installed.

I could replicate locally by manually removing the extension and running the tests locally. The reason why I suspect it's a bug is because after bumping to 11.16.13 it went back to being stable. Will publish a release but you can also specify the newer version of MetaMask in your config/launch options.

**Comment by Wagalidoom** [comment]
> > I still face instabilities on CI, do you know if something is missing @osis ?
> 
> there are known issues with playwright and popups in github actions. I suggest setting up your CI tests to be similar to this repo (retry logic) until they are solved. Looks like running the local test suite is stable.

Hi @osis ! Could you provide more information about this please? I set up 3 retries in the playwright.config.ts but still facing issues on Github Actions (it works properly on local). Thank you

**Comment by osis** [comment]
@Wagalidoom you can take a look at https://github.com/TenKeyLabs/dappwright/blob/5f9d1e0c01cbbeeccfc681340aaadf937d929d8d/.github/workflows/test.yaml#L28-L59

**Comment by osis** [comment]
going to mark this as closed as I can't replicate this specific issue anymore.
