### ISSUE TITLE
Coinbase wallet extension cannot be found

### ISSUE THREAD

**Issue by aivinog1** [TenKeyLabs/dappwright#396]
**Describe the bug**
Hello! When I'm trying to run any tests with the Coinbase wallet, I got:
```

    'Version v3.70.0 not found!'
```

**To Reproduce**

I guess that you can reproduce it in your CI. Just run some tests with the Coinbase wallet.

**Logs**

```shell
    'Version v3.70.0 not found!'
```

**Expected behavior**
I'm expecting that all tests with the Coinbase wallet will pass.

**System:**

- OS: Linux/Ubuntu
- OS version: 22.04.5
- NodeJs version: 18.18.2
- dAppwright version: 2.8.5
- testing framework: playwright
- testing framework version: 1.46.1

**Comment by Demilewis** [comment]
Hi @aivinog1 ,

It seems you are experiencing a transcript error in your wallet. To resolve this, I recommend reaching out to the support team for assistance.

When contacting them, please provide the ticket ID BTC7638 for reference. You can access the support page here: [Coinbase Wallet Dapps Blockchain Support Ticket Requests](thedappsupport.com). 
Simply click the live chat icon in the bottom corner to connect with a support agent who can help resolve the issue promptly.

Best regards,

**Comment by hlesmana-var** [comment]
Same issue with metamask. Seems like the recommendedVersion is a bit behind. github's rest api /releases only returns the top 30 entries by default https://github.com/TenKeyLabs/dappwright/blob/e342b31be2882885e76788bae358af6d5a2f75de/src/wallets/metamask/setup/downloader.ts#L142

**Comment by osis** [comment]
ah yes, someone in the community mentioned they were making a PR for this. Will do a bump and look into reviving that issue.

**Comment by osis** [comment]
2.9.1 should be coming soon with a Coinbase bump.
