### ISSUE TITLE
Outdated examples in readme

### ISSUE THREAD

**Issue by witem** [TenKeyLabs/dappwright#60]
Hi, thanks for this lib! It looks nice) 

I just have a problem with the initial setup:

**Describe the problem**

With the latest version of lib, examples from README don't work, and examples from tests have a bit different structure. Can anybody update the readme with relevant updates? Or at least post it in this issue and I will create a PR with fixes. Thanks!

**System:**

- OS: Linux
- NodeJs version: v16.17.0
- dAppwright version: 2.1.0
- testing framework: @playwright/test
- testing framework version: 1.30.0

**Comment by osis** [comment]
Hey @witem,

sorry for the confusion. What's in the README is an example taking out of a project that uses `@playwright/test` runner to run the tests, while the test runner for this project uses Jest. We would like to switch this project over to keep it aligned but haven't completed that task yet.

What error/issue are you seeing when you try the example setup?

**Comment by witem** [comment]
To reproduce, you can set up a new project and try to use `dappwright`: `npm init playwright@latest`

### Errors in `example.spec.ts`

```
tests/example.spec.ts:10:11 - error TS2740: Type 'DappwrightLaunchResponse' is missing the following properties from type 'BrowserContext': exposeBinding, addInitScript, on, once, and 30 more.

10     const context: BrowserContext = await dappwright.launch("", {
             ~~~~~~~
tests/example.spec.ts:10:65 - error TS2345: Argument of type '{ metamaskVersion: any; }' is not assignable to parameter of type 'OfficialOptions'.
  Type '{ metamaskVersion: any; }' is missing the following properties from type '{ wallet: WalletIdOptions; version: string; }': wallet, version

10     const context: BrowserContext = await dappwright.launch("", {
                                                                   ~
11       metamaskVersion: MetaMaskWallet.recommendedVersion,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12     });
   ~~~~~
tests/example.spec.ts:11:24 - error TS2304: Cannot find name 'MetaMaskWallet'.

11       metamaskVersion: MetaMaskWallet.recommendedVersion,
                          ~~~~~~~~~~~~~~
tests/example.spec.ts:15:11 - error TS2304: Cannot find name 'metamask'.

15     await metamask.unlock();
             ~~~~~~~~
tests/example.spec.ts:36:14 - error TS2551: Property 'waitForUrl' does not exist on type 'Page'. Did you mean 'waitForURL'?

36   await page.waitForUrl("http://localhost:3000/dashboard");
                ~~~~~~~~~~

  node_modules/playwright-core/types/types.d.ts:4594:3
    4594   waitForURL(url: string|RegExp|((url: URL) => boolean), options?: {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4595     /**
         ~~~~~~~
     ...
    4614     waitUntil?: "load"|"domcontentloaded"|"networkidle"|"commit";
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4615   }): Promise<void>;
         ~~~~~~~~~~~~~~~~~~~~
    'waitForURL' is declared here.

```

### Errors in `global-setup.ts`

```
global-setup.ts:2:24 - error TS2307: Cannot find module 'playwright' or its corresponding type declarations.

2 import playwright from 'playwright';
                         ~~~~~~~~~~~~
global-setup.ts:4:36 - error TS2304: Cannot find name 'FullConfig'.

4 async function globalSetup(config: FullConfig) {
```

**Comment by osis** [comment]
we'll definitely take a look. Thanks for reporting this.

**Comment by FranciszekMalcher** [comment]
Same here, trying to add created in global-setup.js wallet in :
`import dappwright, { MetaMaskWallet } from '@tenkeylabs/dappwright';
import playwright from 'playwright';

module.exports = async (config) => {
	const [metamask, page, context] = await dappwright.bootstrap('', {
		wallet: 'metamask',
		version: MetaMaskWallet.recommendedVersion,
	});

	await metamask.importPK('cdd2b7036703e911212e97ca59042b76b0690ac4eafc8ba3d86050b5e23044ec');
	await context.close();
};
`
and that part works well, but implementation in my-test.js
`const base = require('@playwright/test');
import dappwright, { MetaMaskWallet } from '@tenkeylabs/dappwright';

exports.test = base.test.extend({
	context: async ({}, use) => {
		// Launch context with the same session from global-setup
		const context = await dappwright.launch('', {
			metamaskVersion: MetaMaskWallet.recommendedVersion,
		});
		// Unlock the wallet
		await metamask.unlock();
		await use(context);
		await context.close();
	},

	metamask: async ({ context }, use) => {
		const metamask = await dappwright.getWallet('metamask', context);
		await use(metamask);
	},
`

dropping error

`    Error: Wallet undefined not supported

       at my-test.js:10

       8 |      context: async ({}, use) => {
       9 |              // Launch context with the same session from global-setup
    > 10 |              const context = await dappwright.launch('', {
         |                                               ^
      11 |                      metamaskVersion: MetaMaskWallet.recommendedVersion,
      12 |              });
      13 |  `

**Comment by osis** [comment]
README has been updates and there is now an examples repo to help with this https://github.com/TenKeyLabs/dappwright-examples.

**Comment by osis** [comment]
Going to close this since it should be addressed. Let us know if that's not the case.
