### ISSUE TITLE
Support for Polygon

### ISSUE THREAD

**Issue by simeonkerkola** [TenKeyLabs/dappwright#81]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to select Polygon network with: `metamask.switchNetwork('polygon')`

**Comment by osis** [comment]
@hey @simeonkerkola,

you should be able to accomplish this via the `addNetwork` action.

ex.
```
  await metamask.addNetwork({
    networkName: "Hardhat",
    rpc: "http://127.0.0.1:8545/",
    chainId: 31337,
    symbol: "ETH",
  });
```
