### ISSUE TITLE
Need locale option

### ISSUE THREAD

**Issue by ubuygold** [TenKeyLabs/dappwright#94]
Need locale option or add default locale to 'en-US'.
I'm not English user and some regular expressions use text content(in English) as a basis, which may lead to bugs.
![image](https://user-images.githubusercontent.com/10277313/221136713-906e6385-e137-4114-b6fe-87b49b073278.png)

**Comment by ubuygold** [comment]
I've make a fork to change default language to English.
Also fixed [a problem caused by MetaMask](https://github.com/MetaMask/metamask-extension/issues/15629) which will often caused launching failure.

**Comment by ubuygold** [comment]
I've make a [fork ](https://github.com/ubuygold/dappwright)to change default language to English.
Also fixed https://github.com/MetaMask/metamask-extension/issues/15629 which will often causes launching failure.

**Comment by osis** [comment]
Thanks for reporting this. Metamask has been getting better at using `data-testid` in the wallet so that it's not language dependant. This is a good reminder to do another sweep of the metamask selectors overall.
